### ISSUE TITLE
make test success from fork repository

### ISSUE THREAD

**Issue by heleeen** [mackerelio-labs/terraform-provider-mackerel#43]
When I created pull request #42, the test for it was failed since the secrets in this repository could not be read from my fork repository. 
So, we want to update or add tests which don't have to use Mackerel API Key to execute the test.

**Comment by wafuwafu13** [comment]
resolved by https://github.com/mackerelio-labs/terraform-provider-mackerel/pull/116 https://github.com/mackerelio-labs/terraform-provider-mackerel/pull/124
