### ISSUE TITLE
Request: [docs] add role_scopes, monitor_scopes Example to alert_group_setting 

### ISSUE THREAD

**Issue by sogaoh** [mackerelio-labs/terraform-provider-mackerel#59]
In [docs/resources/alert_group_setting](https://registry.terraform.io/providers/mackerelio-labs/mackerel/latest/docs/resources/alert_group_setting), 
it would be nice if there were examples for `role_scopes` and `monitor_scopes` , 
since there are only examples for `service_scopes`.

**Comment by wafuwafu13** [comment]
`role_scopes` and `monitor_scopes` are mentioned in [Attributes Reference](https://registry.terraform.io/providers/mackerelio-labs/mackerel/latest/docs/resources/alert_group_setting#attributes-reference), and we can refer to the [test code](https://github.com/mackerelio-labs/terraform-provider-mackerel/blob/1cbd655f11a5c1c5ec7793d3a560b6b1bebbeb11/mackerel/resource_mackerel_alert_group_setting_test.go#L106-L131) as an example.
