### ISSUE TITLE
[docs] incorrect the example of mackerel_monitor.external

### ISSUE THREAD

**Issue by sogaoh** [mackerelio-labs/terraform-provider-mackerel#62]
About below: 
https://registry.terraform.io/providers/mackerelio-labs/mackerel/latest/docs/resources/monitor#external

I think there is a incorrect statement:

```
headers = { "name" : "Cache-Control", "value" : "no-cache" }
```

I'd like you to correct it:

```
headers = { Cache-Control = "no-cache" }
```

My Example:
- https://github.com/sogaoh/mackerel-practice/blob/master/terraform-provider/serverless-stns/30_Monitor.tf

**Comment by heleeen** [comment]
Thank you for the information 🙏
