### ISSUE TITLE
[docs] incorrect Resource: mackerel_service's argument refference

### ISSUE THREAD

**Issue by yasunori-k** [mackerelio-labs/terraform-provider-mackerel#65]
About below:
https://github.com/mackerelio-labs/terraform-provider-mackerel/blob/main/docs/resources/service.md

I think `name` is the name of **service**, not role. I propose to fix.

**Comment by heleeen** [comment]
fix https://github.com/mackerelio-labs/terraform-provider-mackerel/pull/67

I appreciate for your reporting and fixing this 👍
