### ISSUE TITLE
Add support for DocumentDB to resource mackerel_aws_integration

### ISSUE THREAD

**Issue by keithduncan** [mackerelio-labs/terraform-provider-mackerel#95]
I looked to enable [DocumentDB support](https://mackerel.io/blog/entry/weekly/20220421) for our the AWS integration but found that it isn’t one of the [supported services](https://github.com/mackerelio-labs/terraform-provider-mackerel/blob/15f074be4523821b4f8be1501c706383e5ca040b/mackerel/resource_mackerel_aws_integration.go#L64-L88) in the resource provider yet.

**Comment by heleeen** [comment]
It has released [v0.2.0](https://registry.terraform.io/providers/mackerelio-labs/mackerel/0.2.0) .
Thank you for letting know us!
